apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: jpetstore
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 140.119.19.25
    path: /jpetstore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim 
  namespace: jpetstore
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi